package com.moneylite.core.ui.theme

import androidx.compose.ui.graphics.Color

// Blue-based color palette for Subot

// Primary Blue Colors
val BluePrimary = Color(0xFF1565C0)
val BluePrimaryLight = Color(0xFF5E92F3)
val BluePrimaryDark = Color(0xFF003C8F)

// Light Theme Colors
internal val PrimaryLight = Color(0xFF1565C0)
internal val OnPrimaryLight = Color(0xFFFFFFFF)
internal val PrimaryContainerLight = Color(0xFFD6E3FF)
internal val OnPrimaryContainerLight = Color(0xFF001B3D)
internal val SecondaryLight = Color(0xFF565F71)
internal val OnSecondaryLight = Color(0xFFFFFFFF)
internal val SecondaryContainerLight = Color(0xFFDAE2F9)
internal val OnSecondaryContainerLight = Color(0xFF131C2C)
internal val TertiaryLight = Color(0xFF705574)
internal val OnTertiaryLight = Color(0xFFFFFFFF)
internal val TertiaryContainerLight = Color(0xFFFAD8FC)
internal val OnTertiaryContainerLight = Color(0xFF28132E)
internal val ErrorLight = Color(0xFFBA1A1A)
internal val OnErrorLight = Color(0xFFFFFFFF)
internal val ErrorContainerLight = Color(0xFFFFDAD6)
internal val OnErrorContainerLight = Color(0xFF410002)
internal val BackgroundLight = Color(0xFFFDFBFF)
internal val OnBackgroundLight = Color(0xFF1A1B1E)
internal val SurfaceLight = Color(0xFFFDFBFF)
internal val OnSurfaceLight = Color(0xFF1A1B1E)
internal val SurfaceVariantLight = Color(0xFFE0E2EC)
internal val OnSurfaceVariantLight = Color(0xFF44474E)
internal val OutlineLight = Color(0xFF74777F)
internal val OutlineVariantLight = Color(0xFFC4C6CF)
internal val ScrimLight = Color(0xFF000000)
internal val InverseSurfaceLight = Color(0xFF2F3033)
internal val InverseOnSurfaceLight = Color(0xFFF1F0F4)
internal val InversePrimaryLight = Color(0xFFAAC7FF)
internal val SurfaceDimLight = Color(0xFFDBD9DD)
internal val SurfaceBrightLight = Color(0xFFFDFBFF)
internal val SurfaceContainerLowestLight = Color(0xFFFFFFFF)
internal val SurfaceContainerLowLight = Color(0xFFF5F3F7)
internal val SurfaceContainerLight = Color(0xFFEFEDF1)
internal val SurfaceContainerHighLight = Color(0xFFE9E7EC)
internal val SurfaceContainerHighestLight = Color(0xFFE4E2E6)

// Dark Theme Colors
internal val PrimaryDark = Color(0xFFAAC7FF)
internal val OnPrimaryDark = Color(0xFF002F64)
internal val PrimaryContainerDark = Color(0xFF00458D)
internal val OnPrimaryContainerDark = Color(0xFFD6E3FF)
internal val SecondaryDark = Color(0xFFBEC6DC)
internal val OnSecondaryDark = Color(0xFF283041)
internal val SecondaryContainerDark = Color(0xFF3E4759)
internal val OnSecondaryContainerDark = Color(0xFFDAE2F9)
internal val TertiaryDark = Color(0xFFDDBCDF)
internal val OnTertiaryDark = Color(0xFF3F2844)
internal val TertiaryContainerDark = Color(0xFF573E5B)
internal val OnTertiaryContainerDark = Color(0xFFFAD8FC)
internal val ErrorDark = Color(0xFFFFB4AB)
internal val OnErrorDark = Color(0xFF690005)
internal val ErrorContainerDark = Color(0xFF93000A)
internal val OnErrorContainerDark = Color(0xFFFFDAD6)
internal val BackgroundDark = Color(0xFF121316)
internal val OnBackgroundDark = Color(0xFFE4E2E6)
internal val SurfaceDark = Color(0xFF121316)
internal val OnSurfaceDark = Color(0xFFE4E2E6)
internal val SurfaceVariantDark = Color(0xFF44474E)
internal val OnSurfaceVariantDark = Color(0xFFC4C6CF)
internal val OutlineDark = Color(0xFF8E9099)
internal val OutlineVariantDark = Color(0xFF44474E)
internal val ScrimDark = Color(0xFF000000)
internal val InverseSurfaceDark = Color(0xFFE4E2E6)
internal val InverseOnSurfaceDark = Color(0xFF2F3033)
internal val InversePrimaryDark = Color(0xFF0057B6)
internal val SurfaceDimDark = Color(0xFF121316)
internal val SurfaceBrightDark = Color(0xFF38393C)
internal val SurfaceContainerLowestDark = Color(0xFF0D0E11)
internal val SurfaceContainerLowDark = Color(0xFF1A1B1E)
internal val SurfaceContainerDark = Color(0xFF1E2022)
internal val SurfaceContainerHighDark = Color(0xFF292A2D)
internal val SurfaceContainerHighestDark = Color(0xFF343538)
